import {
  adminProductRoutes,
  authRoutes,
  bannerRoutes,
  brandRoutes,
  cartRoutes,
  categoryRoutes,
  couponRoutes,
  discountRoutes,
  orderRoutes,
  paymentRoutes,
  productRoutes,
  reviewRoutes,
  settingsRoutes,
  userRoutes,
  variantOptionRoutes,
  variantTypeRoutes,
  wishlistRoutes,
} from "./index.js";

export const apiRouteRegistry = Object.freeze([
  { path: "/auth", router: authRoutes },
  { path: "/users", router: userRoutes },
  { path: "/products", router: productRoutes },
  { path: "/admin/products", router: adminProductRoutes },
  { path: "/categories", router: categoryRoutes },
  { path: "/brands", router: brandRoutes },
  { path: "/orders", router: orderRoutes },
  { path: "/cart", router: cartRoutes },
  { path: "/wishlist", router: wishlistRoutes },
  { path: "/coupons", router: couponRoutes },
  { path: "/reviews", router: reviewRoutes },
  { path: "/banners", router: bannerRoutes },
  { path: "/discounts", router: discountRoutes },
  { path: "/settings", router: settingsRoutes },
  { path: "/variant-types", router: variantTypeRoutes },
  { path: "/variant-options", router: variantOptionRoutes },
  { path: "/payments", router: paymentRoutes },
]);
